export declare var onShutDownHandler: (instance: TiWebServer) => ExpressHandler;
export declare var resourceProtectionHandler: (instance: TiWebServer) => ExpressHandler;
export declare var authenticationHandler: (instance: TiWebServer) => ExpressHandler;
export declare var authorizedOAuth2CallbackHandler: (instance: TiWebServer, authMethod: TiAuthMethod) => ExpressHandler;
export declare var logoutHandler: () => ExpressHandler;
export declare var healthHandler: () => ExpressHandler;
export declare var userInformationHandler: () => ExpressHandler;
export declare var httpRedirectHandler: (instance: TiWebServer) => ExpressHandler;
export declare var serviceCallHandler: (instance: TiWebServer) => ExpressHandler;
export declare var invalidRouteHandler: () => ExpressHandler;
export declare var defaultErrorHandler: () => ExpressErrorHandler;
export declare var nonceGenerationHandler: () => ExpressHandler;
export declare var cspHeaderHandler: () => ExpressHandler;
export declare var webAppHandler: (instance: TiWebServer) => ExpressHandler;
export declare var originRefererValidationHandler: (instance: any) => ExpressHandler;
export declare var csrfInitHandler: (instance: TiWebServer) => ExpressHandler;
export declare var csrfProtectionHandler: () => ExpressHandler;
import type { TiAuthMethod } from "#auth-manager";
import type TiWebServer from "#web-server";
export type ExpressRequest = import("express").Request;
export type ExpressResponse = import("express").Response;
export type ExpressHandler = (request: ExpressRequest, response: ExpressResponse, next: (error: Error | null) => void) => void;
export type ExpressErrorHandler = (error: Error, request: ExpressRequest, response: ExpressResponse, next: (error: Error | null) => void) => void;
